add_newline = false

[line_break]
disabled = false

[username]
disabled = false
show_always = true
format = "[$user]($style) on "

[git_status]
disabled=true

[package]
disabled = true

[gcloud]
disabled = true

[hostname]
ssh_only = false
style = "bold dimmed blue"

[docker_context]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[php]
disabled = true

